body_list:
  - base_link
  - front_right_calf
  - front_left_calf
  - hind_right_calf
  - hind_left_calf

noncontact_site_list:
  - imu

contact_site_list:
  - front_right_foot
  - front_left_foot
  - hind_right_foot
  - hind_left_foot

friction_coefficient: 0.8

weights_config:
  base_translational_tracking: 100.0
  base_rotational_tracking: 100.0
  fl_translational_tracking: 10.0
  fl_rotational_tracking: 10.0
  fr_translational_tracking: 10.0
  fr_rotational_tracking: 10.0
  hl_translational_tracking: 10.0
  hl_rotational_tracking: 10.0
  hr_translational_tracking: 10.0
  hr_rotational_tracking: 10.0
  torque: 1.0e-4
  regularization: 1.0e-4
