body_list:
  - torso_left_front_wheel
  - torso_left_rear_wheel
  - torso_right_front_wheel
  - torso_right_rear_wheel
  - head_left_front_wheel
  - head_left_rear_wheel
  - head_right_front_wheel
  - head_right_rear_wheel

noncontact_site_list:


contact_site_list:
  - tlf_wheel_site
  - tlr_wheel_site
  - trf_wheel_site
  - trr_wheel_site
  - hlf_wheel_site
  - hlr_wheel_site
  - hrf_wheel_site
  - hrr_wheel_site

friction_coefficient: 0.8

weights_config:
  base_translational_tracking: 100.0
  base_rotational_tracking: 100.0
  fl_translational_tracking: 10.0
  fl_rotational_tracking: 10.0
  fr_translational_tracking: 10.0
  fr_rotational_tracking: 10.0
  hl_translational_tracking: 10.0
  hl_rotational_tracking: 10.0
  hr_translational_tracking: 10.0
  hr_rotational_tracking: 10.0
  torque: 1.0e-4
  regularization: 1.0e-4
