body_list:
  - torso
  - torso_left_front_wheel
  - torso_left_rear_wheel
  - torso_right_front_wheel
  - torso_right_rear_wheel
  - head
  - head_left_front_wheel
  - head_left_rear_wheel
  - head_right_front_wheel
  - head_right_rear_wheel

noncontact_site_list:
  - torso_site
  - head_site


contact_site_list:
  - tlf_wheel_site
  - tlr_wheel_site
  - trf_wheel_site
  - trr_wheel_site
  - hlf_wheel_site
  - hlr_wheel_site
  - hrf_wheel_site
  - hrr_wheel_site

friction_coefficient: 0.8

weights_config:
  torso_translational_tracking: 100.0
  torso_rotational_tracking: 100.0
  tlf_translational_tracking: 10.0
  tlf_rotational_tracking: 10.0
  tlr_translational_tracking: 10.0
  tlr_rotational_tracking: 10.0
  trf_translational_tracking: 10.0
  trf_rotational_tracking: 10.0
  trr_translational_tracking: 10.0
  trr_rotational_tracking: 10.0
  head_translational_tracking: 100.0
  head_rotational_tracking: 100.0
  hlf_translational_tracking: 10.0
  hlf_rotational_tracking: 10.0
  hlr_translational_tracking: 10.0
  hlr_rotational_tracking: 10.0
  hrf_translational_tracking: 10.0
  hrf_rotational_tracking: 10.0
  hrr_translational_tracking: 10.0
  hrr_rotational_tracking: 10.0
  torque: 1.0e-4
  regularization: 1.0e-4
